### ISSUE TITLE
What GPIO is used to control PWM?

### ISSUE THREAD

**Issue by ArnieX** [tjclement/esp-dimmer-hardware#3]
Hi @tjclement,

which GPIO is used for PWM?

I have just built it myself and it is awesome little board!

![img_1468](https://cloud.githubusercontent.com/assets/2325116/21159868/10ae5e74-c183-11e6-85ba-dcfc170fa3ce.JPG)

Thank you,

Martin

**Comment by tjclement** [comment]
Hi @ArnieX,

Your module looks great, nice job! 

You can check out the example software I wrote for this board [here](https://github.com/tjclement/esp-dimmer-software/). The GPIO used is the ESP's pin 13; if you're using nodeMCU, [this pin is called pin 7](https://github.com/tjclement/esp-dimmer-software/blob/master/pwmServer.lua#L7).

Good luck, and have fun!

Best,
Tom

**Comment by ArnieX** [comment]
Hi @tjclement,

thank you for the quick response. Unfortunately my module had died before I was able to do some serious things. I have no idea what happened and today I fly out to business trip. Have you had similar issue yourself? Now it doesn't even light the strip when connected nor start ESP up. Could that be fried mosfet? How do you exactly set the voltage? I did it to 3.30xV. Do you glue the screw so it couldn't accidantaly change?

Thank you for some hints.

Martin

**Comment by tjclement** [comment]
The ESP datasheet mentions a maximum input voltage of 3.6v, so I set it to ~3.4v. Anecdotally, this increases the chip's stability. Your setting of 3.3v should be fine though, and is definitely not the cause of it not functioning anymore.

I've had failing ESPs on a few of my modules, mostly because of incorrectly set voltage converter settings. Like you said, putting a drop of hot glue on the screw of the voltage converter helps with this problem. I've also had a software issue once that made the device enter a boot loop, which I didn't notice for several hours. This increased its temperature so much it must have overheated. It was unresponsive afterwards.

If the blue LED on the ESP still blinks when you power on your module, the MOSFET or any of the PCB traces may have been fried. If the blue LED doesn't turn on at all, check if the voltage converter still outputs enough volts. If the blue LED remains on continuously, or the ESP gets very hot without doing anything, your ESP has been fried for some reason. If you find out what's wrong, please leave another comment. Perhaps we can improve the module design!

Also related, I'm working on a new version of this board that is even smaller and has 3 channels instead of 1. This allows for dimming traditional RGB LED strips. I've not pushed this to the master branch yet because the design is untested, but I'll push them to a seperate branch when I have a moment. You may find it interesting to look at, too.

**Comment by ArnieX** [comment]
Hi,

that is awesome, I do not need to dim RGB's right now and for this I would likely go for WS2801 which I think is better option, more expensive thought.

Today we have found an issue and it was simply not properly soldered contact on output from DC step down. You can definitely improve your design here, because the converter has each of paired contacts connected together but on your design the two contacts you solder it to aren't connected together. If they were it might have worked in case just part of the soldering is off. But it isn't big deal and the fix is easy too. So if you want to improve this part, just add line between the contacts, or make them bigger to make it one big contact.

Right now I have already ported my FW I used with previous solution to your HW and it works flawlessly. I will be publishing the SW here on GitHub (as it is in Arduino/PlatformIO combo) I would like to ask you if you could reference it from your HW repository as other SW option (if you want of course) as some people prefer LUA and some Arduino.

Thank you for ideas and looking forward to new module. I will definitely check it out.

Martin

**Comment by ArnieX** [comment]
Hi Tom,

here is the firmware https://github.com/ArnieX/esp-dimmer-firmware

BR,

Martin

**Comment by RiRomain** [comment]
@tjclement I've already made a fork of your project and made an RGB driver out of your board :-) :
https://github.com/RiRomain/esp-dimmer-hardware 
It's a little different and not so neat as your little board, I've also used some IRLZ44N as it's what I've used before and it allows for some heat-sink if needed.
I've already assemble some unit, [made an assembly guide](http://www.esp8266color.com/hardware/pcb-soldering/) and it works great for more than a year now! Thanks you for your design.

I'd like to see your new RGB design as your PCB designing skills is much better than mine ^^
